commands_restrictions:
  queue:
    conditions:
      - sender = {{author}}
      - author = onecursor6-oss

queue_rules:
  - name: default
    queue_conditions:
      - base = main
    merge_conditions: []
